couchpotato:
  ports:
  - 5050:5050/tcp
  environment:
    FOLDER: ${folder}
    MOUNTPATH: ${mountpath}
    SERVER: ${server}
    SMBPASSWORD: ${password}
    SMBUSER: ${user}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: lowet84/couchpotato
  privileged: true
  volumes:
  - /volumes/mediaserver/couchpotato:/config
  stdin_open: true
sonarr:
  ports:
  - 8989:8989/tcp
  - 9898:9898/tcp
  environment:
    FOLDER: ${folder}
    MOUNTPATH: ${mountpath}
    SERVER: ${server}
    SMBPASSWORD: ${password}
    SMBUSER: ${user}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: lowet84/sonarr
  privileged: true
  volumes:
  - /volumes/mediaserver/sonarr:/config
  stdin_open: true
plex:
  ports:
  - 32400:32400/tcp
  environment:
    FOLDER: ${folder}
    MOUNTPATH: ${mountpath}
    SERVER: ${server}
    SMBPASSWORD: ${password}
    SMBUSER: ${user}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: lowet84/plex
  privileged: true
  volumes:
  - /volumes/mediaserver/plex:/root
  stdin_open: true
jackett:
  ports:
  - 9117:9117/tcp
  environment:
    JACKETT_KEY: d7nc8w37y4mc9348u9q83mqv
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: lowet84/jackett
  volumes:
  - /volumes/mediaserver/jackett:/root/.config/Jackett
  stdin_open: true
deluge:
  ports:
  - 53211:53211/tcp
  - 8112:8112/tcp
  environment:
    FOLDER: ${folder}
    MOUNTPATH: ${mountpath}
    SERVER: ${server}
    SMBPASSWORD: ${password}
    SMBUSER: ${user}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: lowet84/deluge
  privileged: true
  volumes:
  - /volumes/mediaserver/deluge:/config
  stdin_open: true
balancer:
  ports:
  - 80:80
  labels:
    io.rancher.loadbalancer.target.jackett: jackett.*=9117
    io.rancher.loadbalancer.target.sonarr: sonarr.*=8989
    io.rancher.loadbalancer.target.plex: plex.*=32400
    io.rancher.loadbalancer.target.couchpotato: couchpotato.*=5050
    io.rancher.loadbalancer.target.deluge: deluge.*=8112
  tty: true
  image: rancher/load-balancer-service
  links:
  - deluge:deluge
  - couchpotato:couchpotato
  - sonarr:sonarr
  - jackett:jackett
  - plex:plex
  stdin_open: true
backup:
  environment:
    FOLDER: ${folder}
    MOUNTPATH: ${mountpath}
    SERVER: ${server}
    SMBPASSWORD: ${password}
    SMBUSER: ${user}
    LABEL: ${label}
    INTERVAL: ${interval}
    BACKUPLOCATION: ${backuplocation}
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: lowet84/backup
  privileged: true
  volumes:
  - /volumes/mediaserver:/data
  stdin_open: true
