pydio:
  environment:
    FOLDER: ${folder}
    MOUNTPATH: ${mountpath}
    SERVER: ${server}
    SMBPASSWORD: ${password}
    SMBUSER: ${user}
  ports:
    - 4080:80/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: lowet84/pydio
  privileged: true
  stdin_open: true
