.catalog:
  minimum_rancher_version: v1.0.1
  maintainer: "Fredrik Lowenhamn <fredrik.lowenhamn@gmail.com>"
  name: "Pydio"
  version: "v1.0"
  description: "Pydio is a mature open source software solution for file sharing and synchronization."
  uuid: pydio-0
  questions:
    - variable: "folder"
      description: "SMB share folder"
      label: "SMB folder:"
      required: true
      default: "my_media"
      type: "string"
    - variable: "mountpath"
      description: "Path to mount to, /mnt/<path>"
      label: "Mount path:"
      required: true
      default: "my_share"
      type: "string"
    - variable: "server"
      description: "IP/url of SMB server"
      label: "Server IP:"
      required: true
      default: "127.0.0.1"
      type: "string"
    - variable: "user"
      description: "SMB user"
      label: "SMB User:"
      required: true
      default: "user"
      type: "string"
    - variable: "password"
      description: "SMB password"
      label: "SMB Password:"
      required: true
      default: "password"
      type: "string"

pydio:
  scale: 1
