.catalog:
  name: Mediaserver
  version: 8.5.1-0
  description: |
    Media server with Plex, Couchpotato, Deluge, Jackett and Sonarr
  minimum_rancher_version: v1.01
  maintainer: "Fredrik Löwenhamn <fredrik.lowenhamn@gmail.com>"
  uuid: mediaserver-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"

couchpotato:
  scale: 1
sonarr:
  scale: 1
plex:
  scale: 1
jackett:
  scale: 1
deluge:
  scale: 1
balancer:
  scale: 1
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
backup:
  scale: 1
